[package]
name = "http-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.0"
bytes = "1.0"
thiserror = "2"
httparse = "1.8"
base64 = "0.22"
memchr = "2.7"
tokio = { version = "1", features = ["full"] }
